### ISSUE TITLE
Pip Install Error

### ISSUE THREAD

**Issue by andrewrod33** [concordusapps/python-scim#2]
I'm getting the following when I'm running "pip install scim":

Downloading/unpacking scim
  Downloading scim-0.2.1.tar.gz
  Running setup.py egg_info for package scim
    Traceback (most recent call last):
      File "<string>", line 16, in <module>
      File "link to my path", line 12, in <module>
        'scim').load_module().**version**
    TypeError: load_module() takes exactly 2 arguments (1 given)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 16, in <module>

  File "/Users/sandrew/.virtualenvs/rocketu/build/scim/setup.py", line 12, in <module>

```
'scim').load_module().__version__
```

TypeError: load_module() takes exactly 2 arguments (1 given)

---

Cleaning up...
Command python setup.py egg_info failed with error code 1 in

**Comment by off-by-some** [comment]
@andrewrod33 As far as i know, this needs to be installed with python 3 rather than 2

**Comment by andrewrod33** [comment]
Thank you for information.

**Comment by taystack** [comment]
@Pholey is right. This is a python 3 project.
